trigger:
  branches:
    include:
      - main  # Replace with your branch name if different

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Run your PowerShell scripts here
      # Example:
       .\scripts\1st-line\convert-exelToCsv.ps1
      # .\scripts\2nd-line\script1.ps1
      # .\scripts\infrastructure\script1.ps1
      # etc.

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'utilities/validate-scripts.ps1'
